package com.udacity.astroapp.ui.common

enum class ErrorType {
    NETWORK_ERROR,
    LOADING_PHOTOS_ERROR,
    LOADING_EARTH_PHOTOS_ERROR,
    LOADING_MARS_PHOTOS_ERROR,
    LOADING_ASTEROIDS_ERROR,
    LOADING_OBSERVATORIES_ERROR,
    LOADING_OBSERVATORY_ERROR,
    GENERIC_ERROR
}